#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))
_srchomepath=$(dirname $_srcsbinpath) 
if [ ! -d "$_srcsbinpath/.store" ] ; then
	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/mountservers first." 1>&2
	exit 1
fi
_isatstartup=$1

if [ "$_isatstartup" = "atstartup" ] ; then
	rm -rf $_srcsbinpath/.store/mounted
	sleep 20
	echo "Starting mountservers at........$(date)" > $_srchomepath/startup.log
	nohup $_srcsbinpath/mountservers "ascron" &>> "$_srchomepath/startup.log" &
else
	echo "Starting mountservers at........$(date)" > $_srchomepath/cron.log
	nohup $_srcsbinpath/mountservers "ascron" &>> "$_srchomepath/cron.log" &
fi
exit 0


