#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))
_srchomepath=$(dirname $_srcsbinpath)
_serverlistfile="serverlist.txt"
_mountedfile="$_srcsbinpath/.store/mounted"
_userhome=$HOME

if [ -s "$_srcsbinpath/functions" ] ; then
	. $_srcsbinpath/functions	
else
	echo "$_srcsbinpath/functions file not found!" 1>&2
	exit 1
fi


if [ -f "$_srcsbinpath/$_serverlistfile" ] ; then
	_serverlist="$_srcsbinpath/$_serverlistfile"
elif [ -f "$_srchomepath/$_serverlistfile" ] ; then
	_serverlist="$_srchomepath/$_serverlistfile"
elif [ -f "$_userhome/$_serverlistfile" ] ; then
	_serverlist="$_userhome/$_serverlistfile"
else
	echo "No $_serverlistfile file found in current, previuos or home directory. Create $_serverlistfile file in any of those locations and enter server info as 'user@xxx.xxx.xxx.xxx:/|~/mymounts/mainserver[|long[|time in seconds]]' per line. Things in [] is optional."
	exit 1
fi

readarray _paths < "$_serverlist"
for ln in "${_paths[@]}"
do
	if [ "${ln:0:1}" = "#" ] ; then
		continue
	fi
	#_pparts=($(echo "$ln" | tr "|" " " ))
	strtoarry "$ln" "_pparts" '|'
	
	if [ ${#_pparts[@]} -ne 2 ] ; then
		continue
	fi
	_rpath=${_pparts[0]}
	_mpath=${_pparts[1]}
	_mpath=$(eval echo $_mpath)

	echo "unmounting...$_mpath"
	fusermount -uz "$_mpath"
	grep -v "$_mpath$" "$_mountedfile" | tee "$_mountedfile" 1>/dev/null
		
done

readarray _paths < "$_mountedfile"
for ln in "${_paths[@]}"
do
	if [ "${ln:0:1}" = "#" ] ; then
		continue
	fi
	_mpath=$(eval echo $ln)

	fusermount -uz "$_mpath"
	grep -v "$_mpath$" "$_mountedfile" | tee "$_mountedfile" 1>/dev/null
		
done
